# Generated by Django 4.2.5 on 2023-09-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodwrapper',
            name='foods',
        ),
        migrations.AddField(
            model_name='foodwrapper',
            name='foods',
            field=models.ManyToManyField(related_name='food_wrapper', to='core.primaryitem'),
        ),
    ]
