# Generated by Django 4.2.5 on 2023-09-17 15:13

import app.core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_primaryitem_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodid',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodid',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.core.models.content_data_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])]),
        ),
    ]
