# Generated by Django 4.2.5 on 2023-09-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_foodid_name_foodid_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodwrapper',
            name='foods',
        ),
        migrations.CreateModel(
            name='FoodUnifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.primaryitem')),
                ('food_wrapper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='food_wrappers', to='core.foodwrapper')),
            ],
        ),
        migrations.AddField(
            model_name='foodwrapper',
            name='food_list',
            field=models.ManyToManyField(related_name='wrappers', through='core.FoodUnifier', to='core.primaryitem'),
        ),
    ]
