# Generated by Django 4.2.5 on 2023-09-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_foodwrapper_foods_foodunifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodwrapper',
            name='food_list',
        ),
        migrations.AddField(
            model_name='foodwrapper',
            name='foods',
            field=models.ManyToManyField(related_name='wrappers', to='core.primaryitem'),
        ),
        migrations.DeleteModel(
            name='FoodUnifier',
        ),
    ]
