# Generated by Django 4.2.5 on 2023-09-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_primaryitem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryitem',
            name='parent_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
