# Generated by Django 4.2.5 on 2023-09-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_primaryitem_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryitem',
            name='is_template',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
