# Generated by Django 4.2.5 on 2023-09-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_primaryitem_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
