# Generated by Django 4.2.5 on 2023-09-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_primaryitem_amount'),
        ('orders', '0003_orderfoodunifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_list',
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='orders', through='orders.OrderFoodUnifier', to='core.primaryitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='counted_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
