# Generated by Django 4.2.5 on 2023-09-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderfoodunifier_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
